CREATE DATABASE EventPlus
GO

USE EventPlus


CREATE TABLE TipoUsuario (
	Id_TipoUsuario		UNIQUEIDENTIFIER PRIMARY	KEY DEFAULT ((NEWID())),
	Titulo				NVARCHAR(100)		NOT NULL

)

CREATE TABLE TipoEvento(
	Id_TipoEvento		UNIQUEIDENTIFIER PRIMARY	KEY DEFAULT((NEWID())),
	Titulo				NVARCHAR(100)		NOT NULL

);

CREATE TABLE Instituicao(
	Id_instituicao		UNIQUEIDENTIFIER	PRIMARY		KEY	DEFAULT((NEWID())),
	Endereco			NVARCHAR(100)		NOT NULL,
	NomeFantasia		NVARCHAR(100)		NOT NULL,
	CNPJ				NVARCHAR(14)		NOT NULL	UNIQUE 	

);

CREATE TABLE Usuario(
	Id_usuario			UNIQUEIDENTIFIER	PRIMARY		KEY	DEFAULT((NEWID())),
	Nome				NVARCHAR(100)		NOT NULL,
	Email				NVARCHAR(256)		UNIQUE		NOT NULL,
	Senha				NVARCHAR(60)		NOT NULL,
	Id_TipoUsuario		UNIQUEIDENTIFIER FOREIGN KEY REFERENCES TipoUsuario
	(id_TipoUsuario)

);

CREATE TABLE Evento(
	Id_Evento			UNIQUEIDENTIFIER	PRIMARY		KEY	DEFAULT((NEWID())),
	Nome				NVARCHAR(100)		NOT NULL,
	DataEvento			DATETIME			NOT NULL,
	Descricao			TEXT				NOT NULL,
	Id_TipoEvento		UNIQUEIDENTIFIER FOREIGN KEY REFERENCES TipoEvento
	(Id_TipoEvento),
	Id_Instituicao		UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Instituicao
	(Id_Instituicao)

);

CREATE TABLE Presenca(
	Id_Presenca			UNIQUEIDENTIFIER	PRIMARY		KEY	DEFAULT((NEWID())),
	Situacao			BIT					NOT NULL,
	Id_TipoEvento		UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Evento
	(Id_Evento),
	Id_Usuario			UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Usuario
	(id_Usuario)


)

CREATE TABLE ComentarioEvento(
	Id_ComentarEvento		UNIQUEIDENTIFIER	PRIMARY		KEY	DEFAULT((NEWID())),
	DataComentarioEvento	DATETIME			NOT NULL,
	Descricao				NVARCHAR(200)		NOT NULL,
	Exibe					BIT					NOT NULL,
	Id_TipoEvento			UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Evento
	(Id_Evento),
	Id_Usuario				UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Usuario
	(id_Usuario)


)
